Switch file change gathering

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -195,263 +195,263 @@ jobs:
         uses: davidanson/markdownlint-cli2-action@v6.0.0
         with:
           globs: ${{inputs.changes-md}}
-  build-android:
-    name: Build Android
-    if: inputs.run-build
-    timeout-minutes: 120
-    runs-on: ubuntu-latest
-    container: ghcr.io/wnproject/build-android
-    strategy:
-      fail-fast: false
-      matrix:
-        architecture:
-          - armeabi-v7a
-          - arm64-v8a
-          - x86
-        build-type:
-          - Debug
-          - Release
-    steps:
-      - name: Set up build environment
-        run: mkdir build
-      - name: Checkout
-        uses: actions/checkout@v3.1.0
-        with:
-          path: ./source
-          submodules: true
-      - name: Set up GCS for sccache
-        if: inputs.use-sccache
-        shell: bash
-        run: |
-          KEY_PATH="$RUNNER_TEMP/gcs_key.json"
-          echo "$GCS_KEY" > "$KEY_PATH"
-          echo "SCCACHE_GCS_BUCKET=$GCS_BUCKET" >> $GITHUB_ENV
-          echo "SCCACHE_GCS_KEY_PATH=$KEY_PATH" >> $GITHUB_ENV
-          RW_MODE=$(
-            [ "$INPUTS_SCCACHE_WRITE" == 'true' ] &&
-            echo 'READ_WRITE' ||
-            echo 'READ_ONLY'
-          )
-          echo "SCCACHE_GCS_RW_MODE=$RW_MODE" >> $GITHUB_ENV
-          echo "SCCACHE_IGNORE_SERVER_IO_ERROR=1" >> $GITHUB_ENV
-        env:
-          INPUTS_SCCACHE_WRITE: ${{inputs.sccache-write}}
-          GCS_BUCKET: ${{secrets.SCCACHE_GCS_BUCKET}}
-          GCS_KEY: ${{secrets.SCCACHE_GCS_KEY}}
-      - name: Run configuration
-        working-directory: ./build
-        run: >
-          cmake -GNinja
-          -DCMAKE_BUILD_TYPE="$BUILT_TYPE"
-          -DCMAKE_TOOLCHAIN_FILE="$OVERLAY/android.toolchain.cmake"
-          -DWN_ANDROID_ABIS="$ARCHITECTURE"
-          -DWN_ANDROID_SDK=/opt/android-sdk
-          -DWN_LOW_RESOURCE_MODE=ON
-          -DWN_USE_SCCACHE="$USE_SCCACHE"
-          ../source
-        env:
-          ARCHITECTURE: ${{matrix.architecture}}
-          BUILT_TYPE: ${{matrix.build-type}}
-          OVERLAY: ${{github.workspace}}/source/Overlays/Posix/Overlays/Android
-          USE_SCCACHE: ${{inputs.use-sccache && 'ON' || 'OFF' }}
-      - name: Run build (host tools)
-        working-directory: ./build/host/externals/llvm-project/llvm
-        run: cmake --build . --target llvm-tblgen
-      - name: 'Run build (platform: ${{matrix.architecture}})'
-        working-directory: ./build/${{matrix.architecture}}
-        run: cmake --build .
-      - name: Run build (apks)
-        working-directory: ./build
-        run: cmake --build .
-      - name: Run tests
-        working-directory: ./build
-        run: ctest -C "$BUILD_TYPE" -LE REQUIRES_HARDWARE --output-on-failure
-        env:
-          BUILD_TYPE: ${{matrix.build-type}}
-      - name: Report build details
-        run: du -hbcs ./source ./build
-  build-linux:
-    name: Build Linux
-    if: inputs.run-build
-    timeout-minutes: 120
-    runs-on: ubuntu-latest
-    container: ghcr.io/wnproject/build-linux:${{matrix.compiler}}
-    strategy:
-      fail-fast: false
-      matrix:
-        compiler:
-          - clang-10
-          - clang-11
-          - clang-12
-          - gcc-9
-          - gcc-10
-          - gcc-11
-        build-type:
-          - Debug
-          - Release
-    steps:
-      - name: Set up build environment
-        run: mkdir build
-      - name: Checkout
-        uses: actions/checkout@v3.1.0
-        with:
-          path: ./source
-          submodules: true
-      - name: Set up GCS for sccache
-        if: inputs.use-sccache
-        shell: bash
-        run: |
-          KEY_PATH="$RUNNER_TEMP/gcs_key.json"
-          echo "$GCS_KEY" > "$KEY_PATH"
-          echo "SCCACHE_GCS_BUCKET=$GCS_BUCKET" >> $GITHUB_ENV
-          echo "SCCACHE_GCS_KEY_PATH=$KEY_PATH" >> $GITHUB_ENV
-          RW_MODE=$(
-            [ "$INPUTS_SCCACHE_WRITE" == 'true' ] &&
-            echo 'READ_WRITE' ||
-            echo 'READ_ONLY'
-          )
-          echo "SCCACHE_GCS_RW_MODE=$RW_MODE" >> $GITHUB_ENV
-          echo "SCCACHE_IGNORE_SERVER_IO_ERROR=1" >> $GITHUB_ENV
-        env:
-          INPUTS_SCCACHE_WRITE: ${{inputs.sccache-write}}
-          GCS_BUCKET: ${{secrets.SCCACHE_GCS_BUCKET}}
-          GCS_KEY: ${{secrets.SCCACHE_GCS_KEY}}
-      - name: Run configuration
-        working-directory: ./build
-        run: >
-          cmake -GNinja
-          -DCMAKE_BUILD_TYPE="$BUILD_TYPE"
-          -DWN_LOW_RESOURCE_MODE=ON
-          -DWN_USE_SCCACHE="$USE_SCCACHE"
-          ../source
-        env:
-          BUILD_TYPE: ${{matrix.build-type}}
-          USE_SCCACHE: ${{inputs.use-sccache && 'ON' || 'OFF' }}
-      - name: Run build
-        working-directory: ./build
-        run: cmake --build .
-      - name: Run tests
-        working-directory: ./build
-        run: ctest -C "$BUILD_TYPE" -LE REQUIRES_HARDWARE --output-on-failure
-        env:
-          BUILD_TYPE: ${{matrix.build-type}}
-      - name: Report build details
-        run: du -hbcs ./source ./build
-  build-windows:
-    name: Build Windows
-    if: inputs.run-build
-    timeout-minutes: 120
-    runs-on: windows-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        compiler:
-          - msvc-15
-          - msvc-16
-        build-type:
-          - Debug
-          - Release
-    steps:
-      - name: Set up build environment
-        id: build-environment
-        run: |
-          mkdir build
-          $package = 'ghcr.io/wnproject/build-windows'
-          $docker_image = "${package}:$env:COMPILER".ToLower()
-          "docker-image=$docker_image" >> $env:GITHUB_OUTPUT
-        env:
-          COMPILER: ${{matrix.compiler}}
-      - name: Checkout
-        uses: actions/checkout@v3.1.0
-        with:
-          path: ./source
-          submodules: true
-      - name: Set up GCS for sccache
-        if: inputs.use-sccache
-        shell: bash
-        run: |
-          KEY_PATH="$GITHUB_WORKSPACE/gcs_key.json"
-          echo "$GCS_KEY" > "$KEY_PATH"
-          echo "SCCACHE_GCS_BUCKET=$GCS_BUCKET" >> $GITHUB_ENV
-          RW_MODE=$(
-            [ "$INPUTS_SCCACHE_WRITE" == 'true' ] &&
-            echo 'READ_WRITE' ||
-            echo 'READ_ONLY'
-          )
-          echo "SCCACHE_GCS_RW_MODE=$RW_MODE" >> $GITHUB_ENV
-          echo "SCCACHE_IGNORE_SERVER_IO_ERROR=1" >> $GITHUB_ENV
-        env:
-          INPUTS_SCCACHE_WRITE: ${{inputs.sccache-write}}
-          GCS_BUCKET: ${{secrets.SCCACHE_GCS_BUCKET}}
-          GCS_KEY: ${{secrets.SCCACHE_GCS_KEY}}
-      - name: Pull container
-        run: docker pull $env:DOCKER_IMAGE
-        env:
-          DOCKER_IMAGE: ${{steps.build-environment.outputs.docker-image}}
-      - name: Run configuration
-        run: >
-          docker run --rm
-          -e SCCACHE_GCS_BUCKET="$env:SCCACHE_GCS_BUCKET"
-          -e SCCACHE_GCS_KEY_PATH=C:\workspace\gcs_key.json
-          -e SCCACHE_GCS_RW_MODE="$env:SCCACHE_GCS_RW_MODE"
-          -e SCCACHE_IGNORE_SERVER_IO_ERROR="$env:SCCACHE_IGNORE_SERVER_IO_ERROR"
-          -v ${{github.workspace}}:C:\workspace
-          $env:DOCKER_IMAGE
-          cmake -GNinja -S C:\workspace\source -B C:\workspace\build
-          -DCMAKE_BUILD_TYPE="$env:BUILD_TYPE"
-          -DWN_LOW_RESOURCE_MODE=ON
-          -DWN_USE_SCCACHE="$env:USE_SCCACHE"
-        env:
-          BUILD_TYPE: ${{matrix.build-type}}
-          DOCKER_IMAGE: ${{steps.build-environment.outputs.docker-image}}
-          USE_SCCACHE: ${{inputs.use-sccache && 'ON' || 'OFF' }}
-      - name: Run build
-        run: >
-          docker run --rm
-          -e SCCACHE_GCS_BUCKET="$env:SCCACHE_GCS_BUCKET"
-          -e SCCACHE_GCS_KEY_PATH=C:\workspace\gcs_key.json
-          -e SCCACHE_GCS_RW_MODE="$env:SCCACHE_GCS_RW_MODE"
-          -e SCCACHE_IGNORE_SERVER_IO_ERROR="$env:SCCACHE_IGNORE_SERVER_IO_ERROR"
-          -v ${{github.workspace}}:C:\workspace
-          $env:DOCKER_IMAGE
-          cmake --build C:\workspace\build
-        env:
-          DOCKER_IMAGE: ${{steps.build-environment.outputs.docker-image}}
-      - name: Run tests
-        run: >
-          docker run --rm
-          -v ${{github.workspace}}:C:\workspace
-          $env:DOCKER_IMAGE
-          "cd C:\workspace\build;
-          ctest -C $env:BUILD_TYPE
-          -LE REQUIRES_HARDWARE
-          --output-on-failure"
-        env:
-          BUILD_TYPE: ${{matrix.build-type}}
-          DOCKER_IMAGE: ${{steps.build-environment.outputs.docker-image}}
-      - name: Report build details
-        shell: bash
-        run: du -hbcs ./source ./build
-  build:
-    name: Build
-    needs:
-      - build-android
-      - build-linux
-      - build-windows
-    if: always()
-    timeout-minutes: 5
-    runs-on: ubuntu-latest
-    steps:
-      - name: Accumulate build status
-        shell: bash
-        run: |
-          results=( $BUILD_RESULTS )
-          for result in "${results[@]}"; do
-            if [ "$result" != success ] && [ "$result" != skipped ]; then
-              echo Oh no...☹️ the build has failed!
-              exit 1
-            fi
-          done
-          echo Yay! The build has succeeded! 🎉
-        env:
-          BUILD_RESULTS: ${{join(needs.*.result, ' ')}}
+  # build-android:
+  #   name: Build Android
+  #   if: inputs.run-build
+  #   timeout-minutes: 120
+  #   runs-on: ubuntu-latest
+  #   container: ghcr.io/wnproject/build-android
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       architecture:
+  #         - armeabi-v7a
+  #         - arm64-v8a
+  #         - x86
+  #       build-type:
+  #         - Debug
+  #         - Release
+  #   steps:
+  #     - name: Set up build environment
+  #       run: mkdir build
+  #     - name: Checkout
+  #       uses: actions/checkout@v3.1.0
+  #       with:
+  #         path: ./source
+  #         submodules: true
+  #     - name: Set up GCS for sccache
+  #       if: inputs.use-sccache
+  #       shell: bash
+  #       run: |
+  #         KEY_PATH="$RUNNER_TEMP/gcs_key.json"
+  #         echo "$GCS_KEY" > "$KEY_PATH"
+  #         echo "SCCACHE_GCS_BUCKET=$GCS_BUCKET" >> $GITHUB_ENV
+  #         echo "SCCACHE_GCS_KEY_PATH=$KEY_PATH" >> $GITHUB_ENV
+  #         RW_MODE=$(
+  #           [ "$INPUTS_SCCACHE_WRITE" == 'true' ] &&
+  #           echo 'READ_WRITE' ||
+  #           echo 'READ_ONLY'
+  #         )
+  #         echo "SCCACHE_GCS_RW_MODE=$RW_MODE" >> $GITHUB_ENV
+  #         echo "SCCACHE_IGNORE_SERVER_IO_ERROR=1" >> $GITHUB_ENV
+  #       env:
+  #         INPUTS_SCCACHE_WRITE: ${{inputs.sccache-write}}
+  #         GCS_BUCKET: ${{secrets.SCCACHE_GCS_BUCKET}}
+  #         GCS_KEY: ${{secrets.SCCACHE_GCS_KEY}}
+  #     - name: Run configuration
+  #       working-directory: ./build
+  #       run: >
+  #         cmake -GNinja
+  #         -DCMAKE_BUILD_TYPE="$BUILT_TYPE"
+  #         -DCMAKE_TOOLCHAIN_FILE="$OVERLAY/android.toolchain.cmake"
+  #         -DWN_ANDROID_ABIS="$ARCHITECTURE"
+  #         -DWN_ANDROID_SDK=/opt/android-sdk
+  #         -DWN_LOW_RESOURCE_MODE=ON
+  #         -DWN_USE_SCCACHE="$USE_SCCACHE"
+  #         ../source
+  #       env:
+  #         ARCHITECTURE: ${{matrix.architecture}}
+  #         BUILT_TYPE: ${{matrix.build-type}}
+  #         OVERLAY: ${{github.workspace}}/source/Overlays/Posix/Overlays/Android
+  #         USE_SCCACHE: ${{inputs.use-sccache && 'ON' || 'OFF' }}
+  #     - name: Run build (host tools)
+  #       working-directory: ./build/host/externals/llvm-project/llvm
+  #       run: cmake --build . --target llvm-tblgen
+  #     - name: 'Run build (platform: ${{matrix.architecture}})'
+  #       working-directory: ./build/${{matrix.architecture}}
+  #       run: cmake --build .
+  #     - name: Run build (apks)
+  #       working-directory: ./build
+  #       run: cmake --build .
+  #     - name: Run tests
+  #       working-directory: ./build
+  #       run: ctest -C "$BUILD_TYPE" -LE REQUIRES_HARDWARE --output-on-failure
+  #       env:
+  #         BUILD_TYPE: ${{matrix.build-type}}
+  #     - name: Report build details
+  #       run: du -hbcs ./source ./build
+  # build-linux:
+  #   name: Build Linux
+  #   if: inputs.run-build
+  #   timeout-minutes: 120
+  #   runs-on: ubuntu-latest
+  #   container: ghcr.io/wnproject/build-linux:${{matrix.compiler}}
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       compiler:
+  #         - clang-10
+  #         - clang-11
+  #         - clang-12
+  #         - gcc-9
+  #         - gcc-10
+  #         - gcc-11
+  #       build-type:
+  #         - Debug
+  #         - Release
+  #   steps:
+  #     - name: Set up build environment
+  #       run: mkdir build
+  #     - name: Checkout
+  #       uses: actions/checkout@v3.1.0
+  #       with:
+  #         path: ./source
+  #         submodules: true
+  #     - name: Set up GCS for sccache
+  #       if: inputs.use-sccache
+  #       shell: bash
+  #       run: |
+  #         KEY_PATH="$RUNNER_TEMP/gcs_key.json"
+  #         echo "$GCS_KEY" > "$KEY_PATH"
+  #         echo "SCCACHE_GCS_BUCKET=$GCS_BUCKET" >> $GITHUB_ENV
+  #         echo "SCCACHE_GCS_KEY_PATH=$KEY_PATH" >> $GITHUB_ENV
+  #         RW_MODE=$(
+  #           [ "$INPUTS_SCCACHE_WRITE" == 'true' ] &&
+  #           echo 'READ_WRITE' ||
+  #           echo 'READ_ONLY'
+  #         )
+  #         echo "SCCACHE_GCS_RW_MODE=$RW_MODE" >> $GITHUB_ENV
+  #         echo "SCCACHE_IGNORE_SERVER_IO_ERROR=1" >> $GITHUB_ENV
+  #       env:
+  #         INPUTS_SCCACHE_WRITE: ${{inputs.sccache-write}}
+  #         GCS_BUCKET: ${{secrets.SCCACHE_GCS_BUCKET}}
+  #         GCS_KEY: ${{secrets.SCCACHE_GCS_KEY}}
+  #     - name: Run configuration
+  #       working-directory: ./build
+  #       run: >
+  #         cmake -GNinja
+  #         -DCMAKE_BUILD_TYPE="$BUILD_TYPE"
+  #         -DWN_LOW_RESOURCE_MODE=ON
+  #         -DWN_USE_SCCACHE="$USE_SCCACHE"
+  #         ../source
+  #       env:
+  #         BUILD_TYPE: ${{matrix.build-type}}
+  #         USE_SCCACHE: ${{inputs.use-sccache && 'ON' || 'OFF' }}
+  #     - name: Run build
+  #       working-directory: ./build
+  #       run: cmake --build .
+  #     - name: Run tests
+  #       working-directory: ./build
+  #       run: ctest -C "$BUILD_TYPE" -LE REQUIRES_HARDWARE --output-on-failure
+  #       env:
+  #         BUILD_TYPE: ${{matrix.build-type}}
+  #     - name: Report build details
+  #       run: du -hbcs ./source ./build
+  # build-windows:
+  #   name: Build Windows
+  #   if: inputs.run-build
+  #   timeout-minutes: 120
+  #   runs-on: windows-latest
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       compiler:
+  #         - msvc-15
+  #         - msvc-16
+  #       build-type:
+  #         - Debug
+  #         - Release
+  #   steps:
+  #     - name: Set up build environment
+  #       id: build-environment
+  #       run: |
+  #         mkdir build
+  #         $package = 'ghcr.io/wnproject/build-windows'
+  #         $docker_image = "${package}:$env:COMPILER".ToLower()
+  #         "docker-image=$docker_image" >> $env:GITHUB_OUTPUT
+  #       env:
+  #         COMPILER: ${{matrix.compiler}}
+  #     - name: Checkout
+  #       uses: actions/checkout@v3.1.0
+  #       with:
+  #         path: ./source
+  #         submodules: true
+  #     - name: Set up GCS for sccache
+  #       if: inputs.use-sccache
+  #       shell: bash
+  #       run: |
+  #         KEY_PATH="$GITHUB_WORKSPACE/gcs_key.json"
+  #         echo "$GCS_KEY" > "$KEY_PATH"
+  #         echo "SCCACHE_GCS_BUCKET=$GCS_BUCKET" >> $GITHUB_ENV
+  #         RW_MODE=$(
+  #           [ "$INPUTS_SCCACHE_WRITE" == 'true' ] &&
+  #           echo 'READ_WRITE' ||
+  #           echo 'READ_ONLY'
+  #         )
+  #         echo "SCCACHE_GCS_RW_MODE=$RW_MODE" >> $GITHUB_ENV
+  #         echo "SCCACHE_IGNORE_SERVER_IO_ERROR=1" >> $GITHUB_ENV
+  #       env:
+  #         INPUTS_SCCACHE_WRITE: ${{inputs.sccache-write}}
+  #         GCS_BUCKET: ${{secrets.SCCACHE_GCS_BUCKET}}
+  #         GCS_KEY: ${{secrets.SCCACHE_GCS_KEY}}
+  #     - name: Pull container
+  #       run: docker pull $env:DOCKER_IMAGE
+  #       env:
+  #         DOCKER_IMAGE: ${{steps.build-environment.outputs.docker-image}}
+  #     - name: Run configuration
+  #       run: >
+  #         docker run --rm
+  #         -e SCCACHE_GCS_BUCKET="$env:SCCACHE_GCS_BUCKET"
+  #         -e SCCACHE_GCS_KEY_PATH=C:\workspace\gcs_key.json
+  #         -e SCCACHE_GCS_RW_MODE="$env:SCCACHE_GCS_RW_MODE"
+  #         -e SCCACHE_IGNORE_SERVER_IO_ERROR="$env:SCCACHE_IGNORE_SERVER_IO_ERROR"
+  #         -v ${{github.workspace}}:C:\workspace
+  #         $env:DOCKER_IMAGE
+  #         cmake -GNinja -S C:\workspace\source -B C:\workspace\build
+  #         -DCMAKE_BUILD_TYPE="$env:BUILD_TYPE"
+  #         -DWN_LOW_RESOURCE_MODE=ON
+  #         -DWN_USE_SCCACHE="$env:USE_SCCACHE"
+  #       env:
+  #         BUILD_TYPE: ${{matrix.build-type}}
+  #         DOCKER_IMAGE: ${{steps.build-environment.outputs.docker-image}}
+  #         USE_SCCACHE: ${{inputs.use-sccache && 'ON' || 'OFF' }}
+  #     - name: Run build
+  #       run: >
+  #         docker run --rm
+  #         -e SCCACHE_GCS_BUCKET="$env:SCCACHE_GCS_BUCKET"
+  #         -e SCCACHE_GCS_KEY_PATH=C:\workspace\gcs_key.json
+  #         -e SCCACHE_GCS_RW_MODE="$env:SCCACHE_GCS_RW_MODE"
+  #         -e SCCACHE_IGNORE_SERVER_IO_ERROR="$env:SCCACHE_IGNORE_SERVER_IO_ERROR"
+  #         -v ${{github.workspace}}:C:\workspace
+  #         $env:DOCKER_IMAGE
+  #         cmake --build C:\workspace\build
+  #       env:
+  #         DOCKER_IMAGE: ${{steps.build-environment.outputs.docker-image}}
+  #     - name: Run tests
+  #       run: >
+  #         docker run --rm
+  #         -v ${{github.workspace}}:C:\workspace
+  #         $env:DOCKER_IMAGE
+  #         "cd C:\workspace\build;
+  #         ctest -C $env:BUILD_TYPE
+  #         -LE REQUIRES_HARDWARE
+  #         --output-on-failure"
+  #       env:
+  #         BUILD_TYPE: ${{matrix.build-type}}
+  #         DOCKER_IMAGE: ${{steps.build-environment.outputs.docker-image}}
+  #     - name: Report build details
+  #       shell: bash
+  #       run: du -hbcs ./source ./build
+  # build:
+  #   name: Build
+  #   needs:
+  #     - build-android
+  #     - build-linux
+  #     - build-windows
+  #   if: always()
+  #   timeout-minutes: 5
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Accumulate build status
+  #       shell: bash
+  #       run: |
+  #         results=( $BUILD_RESULTS )
+  #         for result in "${results[@]}"; do
+  #           if [ "$result" != success ] && [ "$result" != skipped ]; then
+  #             echo Oh no...☹️ the build has failed!
+  #             exit 1
+  #           fi
+  #         done
+  #         echo Yay! The build has succeeded! 🎉
+  #       env:
+  #         BUILD_RESULTS: ${{join(needs.*.result, ' ')}}
